CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "DisplayName" text,
    "AvatarUrl" text,
    "TenantId" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastLoginAt" timestamp with time zone,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE collections (
    "Id" uuid NOT NULL,
    "Name" character varying(255) NOT NULL,
    "Description" text,
    "Settings" jsonb,
    "IsDefault" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_collections" PRIMARY KEY ("Id")
);

CREATE TABLE entities (
    "Id" uuid NOT NULL,
    "CanonicalName" character varying(500) NOT NULL,
    "EntityType" character varying(50) NOT NULL,
    "Description" text,
    "Aliases" text[] NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_entities" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE collection_salient_terms (
    "Id" uuid NOT NULL,
    "CollectionId" uuid NOT NULL,
    "Term" character varying(200) NOT NULL,
    "NormalizedTerm" character varying(200) NOT NULL,
    "Score" double precision NOT NULL,
    "Source" character varying(32) NOT NULL,
    "DocumentFrequency" integer NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_collection_salient_terms" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_collection_salient_terms_collections_CollectionId" FOREIGN KEY ("CollectionId") REFERENCES collections ("Id") ON DELETE CASCADE
);

CREATE TABLE communities (
    "Id" uuid NOT NULL,
    "CollectionId" uuid NOT NULL,
    "Name" character varying(512) NOT NULL,
    "Summary" text,
    "Features" jsonb,
    "Algorithm" character varying(64) NOT NULL,
    "Level" integer NOT NULL,
    "ParentCommunityId" uuid,
    "EntityCount" integer NOT NULL,
    "Cohesion" real NOT NULL,
    "Embedding" jsonb,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_communities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_communities_collections_CollectionId" FOREIGN KEY ("CollectionId") REFERENCES collections ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_communities_communities_ParentCommunityId" FOREIGN KEY ("ParentCommunityId") REFERENCES communities ("Id") ON DELETE SET NULL
);

CREATE TABLE conversations (
    "Id" uuid NOT NULL,
    "CollectionId" uuid,
    "Title" character varying(255),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_conversations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_conversations_collections_CollectionId" FOREIGN KEY ("CollectionId") REFERENCES collections ("Id") ON DELETE SET NULL
);

CREATE TABLE documents (
    "Id" uuid NOT NULL,
    "CollectionId" uuid,
    "Name" character varying(500) NOT NULL,
    "OriginalFilename" character varying(500),
    "ContentHash" character varying(64) NOT NULL,
    "FilePath" character varying(1000),
    "FileSizeBytes" bigint,
    "MimeType" character varying(100),
    "Status" character varying(50) NOT NULL,
    "StatusMessage" text,
    "ProcessingProgress" real NOT NULL,
    "SegmentCount" integer NOT NULL,
    "EntityCount" integer NOT NULL,
    "TableCount" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ProcessedAt" timestamp with time zone,
    "Metadata" jsonb,
    "SourceUrl" character varying(2000),
    "SourcePath" text,
    "SourceCreatedAt" timestamp with time zone,
    "SourceModifiedAt" timestamp with time zone,
    "Version" integer NOT NULL,
    "VectorStoreDocId" text,
    CONSTRAINT "PK_documents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_documents_collections_CollectionId" FOREIGN KEY ("CollectionId") REFERENCES collections ("Id") ON DELETE CASCADE
);

CREATE TABLE ingestion_sources (
    "Id" uuid NOT NULL,
    "Name" character varying(255) NOT NULL,
    "SourceType" character varying(32) NOT NULL,
    "Location" character varying(2048) NOT NULL,
    "FilePattern" character varying(256),
    "Recursive" boolean NOT NULL,
    "CollectionId" uuid,
    "Options" jsonb,
    "Credentials" character varying(4096),
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastSyncAt" timestamp with time zone,
    "TotalItemsIngested" integer NOT NULL,
    "IsEnabled" boolean NOT NULL,
    CONSTRAINT "PK_ingestion_sources" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ingestion_sources_collections_CollectionId" FOREIGN KEY ("CollectionId") REFERENCES collections ("Id") ON DELETE SET NULL
);

CREATE TABLE retrieval_entities (
    "Id" uuid NOT NULL,
    "ContentType" character varying(32) NOT NULL,
    "Source" character varying(2048) NOT NULL,
    "ContentHash" character varying(64),
    "CollectionId" uuid,
    "Title" character varying(512),
    "Summary" character varying(4000),
    "TextContent" text,
    "EmbeddingModel" character varying(128),
    "QualityScore" double precision NOT NULL,
    "ContentConfidence" double precision NOT NULL,
    "NeedsReview" boolean NOT NULL,
    "ReviewReason" character varying(1000),
    "Tags" jsonb,
    "Metadata" jsonb,
    "CustomMetadata" jsonb,
    "Signals" jsonb,
    "ExtractedEntities" jsonb,
    "Relationships" jsonb,
    "SourceModalities" jsonb,
    "ProcessingState" jsonb,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_retrieval_entities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_retrieval_entities_collections_CollectionId" FOREIGN KEY ("CollectionId") REFERENCES collections ("Id") ON DELETE SET NULL
);

CREATE TABLE scanned_page_groups (
    "Id" uuid NOT NULL,
    "CollectionId" uuid,
    "GroupName" character varying(512) NOT NULL,
    "GroupingStrategy" character varying(32) NOT NULL,
    "FilenamePattern" character varying(256),
    "DirectoryPath" character varying(1024),
    "Metadata" jsonb,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_scanned_page_groups" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_scanned_page_groups_collections_CollectionId" FOREIGN KEY ("CollectionId") REFERENCES collections ("Id") ON DELETE CASCADE
);

CREATE TABLE entity_relationships (
    "Id" uuid NOT NULL,
    "SourceEntityId" uuid NOT NULL,
    "TargetEntityId" uuid NOT NULL,
    "RelationshipType" character varying(100) NOT NULL,
    "Strength" real NOT NULL,
    "SourceDocuments" uuid[] NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_entity_relationships" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_entity_relationships_entities_SourceEntityId" FOREIGN KEY ("SourceEntityId") REFERENCES entities ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_entity_relationships_entities_TargetEntityId" FOREIGN KEY ("TargetEntityId") REFERENCES entities ("Id") ON DELETE CASCADE
);

CREATE TABLE community_memberships (
    "CommunityId" uuid NOT NULL,
    "EntityId" uuid NOT NULL,
    "Centrality" real NOT NULL,
    "IsRepresentative" boolean NOT NULL,
    CONSTRAINT "PK_community_memberships" PRIMARY KEY ("CommunityId", "EntityId"),
    CONSTRAINT "FK_community_memberships_communities_CommunityId" FOREIGN KEY ("CommunityId") REFERENCES communities ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_community_memberships_entities_EntityId" FOREIGN KEY ("EntityId") REFERENCES entities ("Id") ON DELETE CASCADE
);

CREATE TABLE conversation_messages (
    "Id" uuid NOT NULL,
    "ConversationId" uuid NOT NULL,
    "Role" character varying(20) NOT NULL,
    "Content" text NOT NULL,
    "Metadata" jsonb,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_conversation_messages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_conversation_messages_conversations_ConversationId" FOREIGN KEY ("ConversationId") REFERENCES conversations ("Id") ON DELETE CASCADE
);

CREATE TABLE document_entities (
    "DocumentId" uuid NOT NULL,
    "EntityId" uuid NOT NULL,
    "MentionCount" integer NOT NULL,
    "SegmentIds" text[] NOT NULL,
    "FirstSeenAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_document_entities" PRIMARY KEY ("DocumentId", "EntityId"),
    CONSTRAINT "FK_document_entities_documents_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES documents ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_document_entities_entities_EntityId" FOREIGN KEY ("EntityId") REFERENCES entities ("Id") ON DELETE CASCADE
);

CREATE TABLE ingestion_jobs (
    "Id" uuid NOT NULL,
    "SourceId" uuid NOT NULL,
    "Status" character varying(32) NOT NULL,
    "ItemsDiscovered" integer NOT NULL,
    "ItemsProcessed" integer NOT NULL,
    "ItemsFailed" integer NOT NULL,
    "ItemsSkipped" integer NOT NULL,
    "ErrorMessage" text,
    "Errors" jsonb,
    "IncrementalSync" boolean NOT NULL,
    "MaxItems" integer NOT NULL,
    "Priority" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "StartedAt" timestamp with time zone,
    "CompletedAt" timestamp with time zone,
    CONSTRAINT "PK_ingestion_jobs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ingestion_jobs_ingestion_sources_SourceId" FOREIGN KEY ("SourceId") REFERENCES ingestion_sources ("Id") ON DELETE CASCADE
);

CREATE TABLE entity_embeddings (
    "Id" uuid NOT NULL,
    "EntityId" uuid NOT NULL,
    "Name" character varying(64) NOT NULL,
    "Model" character varying(128),
    "Dimension" integer NOT NULL,
    "Vector" jsonb,
    "VectorBinary" bytea,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_entity_embeddings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_entity_embeddings_retrieval_entities_EntityId" FOREIGN KEY ("EntityId") REFERENCES retrieval_entities ("Id") ON DELETE CASCADE
);

CREATE TABLE evidence_artifacts (
    "Id" uuid NOT NULL,
    "EntityId" uuid NOT NULL,
    "ArtifactType" character varying(64) NOT NULL,
    "MimeType" character varying(128) NOT NULL,
    "StorageBackend" character varying(32) NOT NULL,
    "StoragePath" character varying(2048) NOT NULL,
    "FileSizeBytes" bigint NOT NULL,
    "ContentHash" character varying(64),
    "SegmentHash" character varying(32),
    "Content" text,
    "ProducerSource" character varying(128),
    "ProducerVersion" character varying(32),
    "Confidence" double precision,
    "Metadata" jsonb,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone,
    CONSTRAINT "PK_evidence_artifacts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_evidence_artifacts_retrieval_entities_EntityId" FOREIGN KEY ("EntityId") REFERENCES retrieval_entities ("Id") ON DELETE CASCADE
);

CREATE TABLE scanned_page_memberships (
    "GroupId" uuid NOT NULL,
    "EntityId" uuid NOT NULL,
    "PageNumber" integer NOT NULL,
    "OriginalFilename" character varying(512),
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_scanned_page_memberships" PRIMARY KEY ("GroupId", "EntityId"),
    CONSTRAINT "FK_scanned_page_memberships_retrieval_entities_EntityId" FOREIGN KEY ("EntityId") REFERENCES retrieval_entities ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_scanned_page_memberships_scanned_page_groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES scanned_page_groups ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_collection_salient_terms_CollectionId_NormalizedTerm" ON collection_salient_terms ("CollectionId", "NormalizedTerm");

CREATE INDEX "IX_collection_salient_terms_CollectionId_Score" ON collection_salient_terms ("CollectionId", "Score");

CREATE INDEX "IX_collection_salient_terms_UpdatedAt" ON collection_salient_terms ("UpdatedAt");

CREATE INDEX "IX_collections_Name" ON collections ("Name");

CREATE INDEX "IX_communities_CollectionId" ON communities ("CollectionId");

CREATE UNIQUE INDEX "IX_communities_CollectionId_Name" ON communities ("CollectionId", "Name");

CREATE INDEX "IX_communities_EntityCount" ON communities ("EntityCount");

CREATE INDEX "IX_communities_Level" ON communities ("Level");

CREATE INDEX "IX_communities_ParentCommunityId" ON communities ("ParentCommunityId");

CREATE INDEX "IX_community_memberships_Centrality" ON community_memberships ("Centrality");

CREATE INDEX "IX_community_memberships_EntityId" ON community_memberships ("EntityId");

CREATE INDEX "IX_conversation_messages_ConversationId" ON conversation_messages ("ConversationId");

CREATE INDEX "IX_conversations_CollectionId" ON conversations ("CollectionId");

CREATE INDEX "IX_document_entities_EntityId" ON document_entities ("EntityId");

CREATE INDEX "IX_documents_CollectionId" ON documents ("CollectionId");

CREATE INDEX "IX_documents_ContentHash" ON documents ("ContentHash");

CREATE INDEX "IX_documents_SourceUrl" ON documents ("SourceUrl");

CREATE INDEX "IX_documents_Status" ON documents ("Status");

CREATE UNIQUE INDEX "IX_entities_CanonicalName_EntityType" ON entities ("CanonicalName", "EntityType");

CREATE INDEX "IX_entities_EntityType" ON entities ("EntityType");

CREATE INDEX "IX_entity_embeddings_EntityId" ON entity_embeddings ("EntityId");

CREATE UNIQUE INDEX "IX_entity_embeddings_EntityId_Name" ON entity_embeddings ("EntityId", "Name");

CREATE INDEX "IX_entity_relationships_RelationshipType" ON entity_relationships ("RelationshipType");

CREATE INDEX "IX_entity_relationships_SourceEntityId" ON entity_relationships ("SourceEntityId");

CREATE INDEX "IX_entity_relationships_TargetEntityId" ON entity_relationships ("TargetEntityId");

CREATE INDEX "IX_evidence_artifacts_ArtifactType" ON evidence_artifacts ("ArtifactType");

CREATE INDEX "IX_evidence_artifacts_ContentHash" ON evidence_artifacts ("ContentHash");

CREATE INDEX "IX_evidence_artifacts_EntityId" ON evidence_artifacts ("EntityId");

CREATE INDEX "IX_evidence_artifacts_EntityId_ArtifactType" ON evidence_artifacts ("EntityId", "ArtifactType");

CREATE INDEX "IX_evidence_artifacts_Metadata" ON evidence_artifacts USING gin ("Metadata");

CREATE INDEX "IX_evidence_artifacts_SegmentHash" ON evidence_artifacts ("SegmentHash");

CREATE INDEX "IX_ingestion_jobs_CreatedAt" ON ingestion_jobs ("CreatedAt");

CREATE INDEX "IX_ingestion_jobs_SourceId" ON ingestion_jobs ("SourceId");

CREATE INDEX "IX_ingestion_jobs_Status" ON ingestion_jobs ("Status");

CREATE INDEX "IX_ingestion_sources_CollectionId" ON ingestion_sources ("CollectionId");

CREATE INDEX "IX_ingestion_sources_IsEnabled" ON ingestion_sources ("IsEnabled");

CREATE INDEX "IX_ingestion_sources_Name" ON ingestion_sources ("Name");

CREATE INDEX "IX_ingestion_sources_SourceType" ON ingestion_sources ("SourceType");

CREATE INDEX "IX_retrieval_entities_CollectionId" ON retrieval_entities ("CollectionId");

CREATE INDEX "IX_retrieval_entities_CollectionId_ContentType" ON retrieval_entities ("CollectionId", "ContentType");

CREATE INDEX "IX_retrieval_entities_ContentHash" ON retrieval_entities ("ContentHash");

CREATE INDEX "IX_retrieval_entities_ContentType" ON retrieval_entities ("ContentType");

CREATE INDEX "IX_retrieval_entities_CreatedAt" ON retrieval_entities ("CreatedAt");

CREATE INDEX "IX_retrieval_entities_NeedsReview" ON retrieval_entities ("NeedsReview");

CREATE INDEX "IX_scanned_page_groups_CollectionId" ON scanned_page_groups ("CollectionId");

CREATE INDEX "IX_scanned_page_groups_GroupingStrategy" ON scanned_page_groups ("GroupingStrategy");

CREATE INDEX "IX_scanned_page_memberships_EntityId" ON scanned_page_memberships ("EntityId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260111113625_InitialCreate', '10.0.1');

COMMIT;

