using System.Text.Json.Serialization;
using DoomSummarizer.Models;

namespace DoomSummarizer.Services;

/// <summary>
///     Structured intent output from the sentinel LLM.
///     The sentinel classifies the query into structured parameters (categories, tone, intent)
///     instead of selecting specific sources — source selection is done heuristically
///     by <see cref="SentinelSourceMapper" />.
/// </summary>
public record SentinelIntent
{
    /// <summary>
    ///     Query intent type: news, research, howto, roundup, opinion, qa, deep_dive, trend, comparison.
    /// </summary>
    [JsonPropertyName("intent")]
    public string Intent { get; init; } = "news";

    /// <summary>
    ///     Category weights (0.0–1.0). Keys match sources.yaml routing categories:
    ///     technology, programming, health, pharma, science, environment, climate,
    ///     business, finance, politics, world, entertainment, humor, sports,
    ///     ai, security, space, disaster, factcheck.
    /// </summary>
    [JsonPropertyName("categories")]
    public Dictionary<string, double> Categories { get; init; } = new();

    /// <summary>
    ///     Output tone: neutral, doom, hopeful, snarky, funny, upbeat, friendly.
    /// </summary>
    [JsonPropertyName("tone")]
    public string Tone { get; init; } = "neutral";

    /// <summary>
    ///     How time-sensitive is this query: breaking, today, week, any.
    /// </summary>
    [JsonPropertyName("time_sensitivity")]
    public string TimeSensitivity { get; init; } = "any";

    // ─── Temporal Extraction (NEW) ───

    /// <summary>
    ///     Parsed date range for the query. Extracted from natural language like
    ///     "last week", "since Monday", "past 3 days", "January 2024".
    /// </summary>
    [JsonPropertyName("date_range")]
    public DateRangeIntent? DateRange { get; init; }

    /// <summary>
    ///     Whether this query requires fresh data (skip cache).
    ///     True for: "latest", "breaking", "right now", "just happened".
    /// </summary>
    [JsonPropertyName("requires_fresh")]
    public bool RequiresFresh { get; init; }

    /// <summary>
    ///     Whether this is a continuation query referencing previous results.
    ///     True for: "since last time", "more like this", "update on", "any changes".
    /// </summary>
    [JsonPropertyName("is_continuation")]
    public bool IsContinuation { get; init; }

    /// <summary>
    ///     Whether this query asks about change/drift over time.
    ///     True for: "how has X changed", "sentiment shift", "evolution of", "trend in".
    ///     Enables temporal comparison mode.
    /// </summary>
    [JsonPropertyName("is_temporal_comparison")]
    public bool IsTemporalComparison { get; init; }

    /// <summary>
    ///     Reference topic for continuation queries (what to continue from).
    ///     E.g., for "any updates on the trial?", this would be "trial" or the entity name.
    /// </summary>
    [JsonPropertyName("continuation_topic")]
    public string? ContinuationTopic { get; init; }

    // ─── Query Enhancement Fields ───

    /// <summary>
    ///     Spellchecked/corrected version of the user's query.
    ///     Fixes common typos, expands abbreviations (SNL → Saturday Night Live).
    ///     Used as the canonical query text for all downstream filtering.
    /// </summary>
    [JsonPropertyName("corrected_query")]
    public string? CorrectedQuery { get; init; }

    /// <summary>
    ///     Filter keywords for Lucene/SQLite pre-filtering.
    ///     These are the core salient terms that MUST appear in relevant documents.
    ///     Excludes stop words and low-information terms.
    ///     Example: "history of LLMs" → ["llm", "llms", "language model", "history"]
    /// </summary>
    [JsonPropertyName("filter_keywords")]
    public List<string> FilterKeywords { get; init; } = [];

    /// <summary>
    ///     Lucene query syntax for advanced filtering.
    ///     Generated by sentinel with proper boosting, fuzzy, and phrase operators.
    ///     Example: "title:LLM^3 \"language model\"~2 history~"
    ///     If empty, use FilterKeywords with simple OR logic.
    /// </summary>
    [JsonPropertyName("lucene_query")]
    public string? LuceneQuery { get; init; }

    // ─── Search Engine Query Fields ───

    /// <summary>
    ///     Specific search terms to use for search-based sources (gnews, duckduckgo).
    /// </summary>
    [JsonPropertyName("search_queries")]
    public List<string> SearchQueries { get; init; } = [];

    /// <summary>
    ///     Named entities extracted by the sentinel (people, orgs, places).
    /// </summary>
    [JsonPropertyName("entities")]
    public List<string> Entities { get; init; } = [];

    /// <summary>
    ///     Sources the user explicitly named (e.g., "hacker news" → "hn", "bbc" → "bbc").
    ///     Only populated when the user directly references a source by name.
    /// </summary>
    [JsonPropertyName("explicit_sources")]
    public List<string> ExplicitSources { get; init; } = [];

    /// <summary>
    ///     Requested item limit.
    /// </summary>
    [JsonPropertyName("limit")]
    public int Limit { get; init; } = 20;

    /// <summary>
    ///     GraphRAG query scope: "local" (specific), "global" (sensemaking), "connective" (DRIFT).
    ///     When "global" or "connective", entity graph enrichment is auto-enabled.
    ///     See: https://microsoft.github.io/graphrag/
    /// </summary>
    [JsonPropertyName("graph_scope")]
    public string? GraphScope { get; init; }

    // ─── Query Decomposition (Composite Questions) ───

    /// <summary>
    ///     For composite questions (multiple sub-questions joined by "and", "also", etc.),
    ///     this contains the decomposed subqueries that should be answered separately.
    ///     Example: "What happens in Wuthering Heights and when was the latest movie made?"
    ///     → ["What happens in Wuthering Heights?", "When was the latest Wuthering Heights movie made?"]
    /// </summary>
    [JsonPropertyName("subqueries")]
    public List<string>? Subqueries { get; init; }

    /// <summary>
    ///     True if the query contains multiple distinct sub-questions that need separate answers.
    /// </summary>
    [JsonPropertyName("is_composite")]
    public bool IsComposite { get; init; }

    /// <summary>
    ///     True if decomposed subqueries were provided.
    /// </summary>
    public bool HasSubqueries => Subqueries is { Count: > 1 };
}

/// <summary>
///     Parsed date range from natural language temporal expressions.
/// </summary>
public record DateRangeIntent
{
    /// <summary>
    ///     Start of the date range (null = no lower bound).
    ///     ISO 8601 format: "2024-01-15" or "2024-01-15T10:00:00Z".
    /// </summary>
    [JsonPropertyName("start")]
    public string? Start { get; init; }

    /// <summary>
    ///     End of the date range (null = now).
    ///     ISO 8601 format: "2024-01-22" or "2024-01-22T23:59:59Z".
    /// </summary>
    [JsonPropertyName("end")]
    public string? End { get; init; }

    /// <summary>
    ///     Original natural language expression that was parsed.
    ///     E.g., "last week", "since Monday", "past 3 days".
    /// </summary>
    [JsonPropertyName("original")]
    public string? Original { get; init; }

    /// <summary>
    ///     Relative time unit if applicable: hour, day, week, month, year.
    /// </summary>
    [JsonPropertyName("unit")]
    public string? Unit { get; init; }

    /// <summary>
    ///     Number of units (e.g., 3 for "past 3 days").
    /// </summary>
    [JsonPropertyName("count")]
    public int? Count { get; init; }

    /// <summary>
    ///     Parse the Start string to DateTimeOffset (returns null if unparseable).
    /// </summary>
    public DateTimeOffset? ParsedStart => TryParse(Start);

    /// <summary>
    ///     Parse the End string to DateTimeOffset (returns null if unparseable).
    /// </summary>
    public DateTimeOffset? ParsedEnd => TryParse(End);

    private static DateTimeOffset? TryParse(string? s)
    {
        return DateTimeOffset.TryParse(s, out var dt) ? dt : null;
    }
}

/// <summary>
///     Heuristically maps a <see cref="SentinelIntent" /> to concrete CLI source identifiers
///     using the YAML-driven <see cref="SourceRouter" /> routing rules.
///     The sentinel LLM only classifies the query — this class picks the actual sources.
/// </summary>
public static class SentinelSourceMapper
{
    /// <summary>
    ///     Default maximum total sources to select (avoids excessive fetching).
    ///     Overridden per-intent in <see cref="MapToSources" />.
    /// </summary>
    private const int DefaultMaxTotalSources = 10;

    /// <summary>
    ///     Minimum category weight to include sources from that category.
    /// </summary>
    private const double MinCategoryWeight = 0.15;

    /// <summary>
    ///     Categories that imply tech content.
    ///     Shared with <see cref="PromptInterpreter" /> for consistent tech-source filtering.
    /// </summary>
    private static readonly HashSet<string> TechCategories = new(StringComparer.OrdinalIgnoreCase)
    {
        "technology", "programming", "ai", "security"
    };

    /// <summary>
    ///     Valid YAML routing categories. Used to validate sentinel output.
    /// </summary>
    private static readonly HashSet<string> ValidCategories = new(StringComparer.OrdinalIgnoreCase)
    {
        "technology", "ai", "security", "programming", "science", "health", "pharma",
        "business", "finance", "politics", "world", "entertainment", "humor", "sports",
        "environment", "climate", "space", "disaster", "factcheck",
        "uk_politics", "crime", "flooding", "uk", // UK-specific routing categories
        "default"
    };

    /// <summary>
    ///     Map unknown sentinel categories to valid routing categories.
    ///     Local LLMs sometimes invent categories not in our YAML routing.
    /// </summary>
    private static readonly Dictionary<string, string> CategoryAliases = new(StringComparer.OrdinalIgnoreCase)
    {
        ["geography"] = "world",
        ["news"] = "default",
        ["general"] = "default",
        ["culture"] = "entertainment",
        ["education"] = "science",
        ["travel"] = "world",
        ["food"] = "default",
        ["law"] = "politics",
        ["legal"] = "politics",
        ["military"] = "world",
        ["energy"] = "environment",
        ["crypto"] = "finance",
        ["gaming"] = "technology",
        ["llm"] = "ai",
        ["llms"] = "ai",
        ["machine_learning"] = "ai",
        ["robotics"] = "technology",
        ["music"] = "entertainment",
        ["film"] = "entertainment",
        ["tv"] = "entertainment",
        ["medicine"] = "health",
        ["weather"] = "environment",
        ["astronomy"] = "space",
        ["economics"] = "business",
        ["flood"] = "flooding",
        ["floods"] = "flooding",
        ["policing"] = "crime",
        ["parliament"] = "uk_politics"
    };

    /// <summary>
    ///     Map a sentinel intent to concrete source identifiers for the fetch pipeline.
    /// </summary>
    /// <param name="intent">Structured intent from sentinel LLM.</param>
    /// <param name="router">YAML source router for category → source lookups.</param>
    /// <param name="query">Original user query (for search source parameterization).</param>
    /// <param name="nerContext">Optional NER context for entity-specific source enrichment.</param>
    /// <returns>Ordered list of CLI source identifiers (e.g., "gnews:AI news", "bbc:technology", "hn").</returns>
    public static List<string> MapToSources(
        SentinelIntent intent,
        SourceRouter router,
        string query,
        QueryNerContext? nerContext = null)
    {
        var sources = new List<string>();
        var usedRoots = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        // Adaptive source cap: focused queries need fewer sources to reduce irrelevant fetches
        var maxTotalSources = intent.Intent switch
        {
            "qa" or "howto" => 5, // room for wikipedia + search + a few feeds
            "deep_dive" or "research" => 8, // room for arxiv/wikipedia enrichment
            _ => DefaultMaxTotalSources
        };

        // Null-guard all collection properties — JSON deserialization can set them to null
        // even though the record has default initializers.
        var categories = intent.Categories ?? new Dictionary<string, double>();
        var explicitSources = intent.ExplicitSources ?? [];
        var intentSearchQueries = intent.SearchQueries ?? [];

        var isRoundup = intent.Intent is "roundup" or "news" &&
                        intent.TimeSensitivity is "today" or "breaking";
        var isQA = intent.Intent is "qa" or "howto";
        var isSearchOnly = intent.Intent is "search_only";
        var hasTechCategory = categories.Any(c =>
            TechCategories.Contains(c.Key) && c.Value >= MinCategoryWeight);
        var timeSensitivity = intent.TimeSensitivity ?? "any";

        // --- Phase 1: Explicit user-named sources (always honored) ---
        foreach (var src in explicitSources) AddSource(sources, usedRoots, src);

        // --- Phase 2: Score-based selection ---
        // Normalize categories in a single pass (no GroupBy — track max per normalized key)
        var normalizedCategories = new Dictionary<string, double>(StringComparer.OrdinalIgnoreCase);
        foreach (var (key, weight) in categories)
        {
            if (weight < MinCategoryWeight) continue;
            var normalized = ValidCategories.Contains(key)
                ? key
                : CategoryAliases.GetValueOrDefault(key, "default");
            if (normalized == "default") continue;

            if (normalizedCategories.TryGetValue(normalized, out var existing))
                normalizedCategories[normalized] = Math.Max(existing, weight);
            else
                normalizedCategories[normalized] = weight;
        }

        var sortedCategories = normalizedCategories
            .OrderByDescending(kv => kv.Value)
            .Select(kv => new KeyValuePair<string, double>(kv.Key, kv.Value))
            .ToList();

        if (sortedCategories.Count == 0)
            sortedCategories = [new KeyValuePair<string, double>("default", 0.5)];

        // Cache routing results to avoid repeated RouteByTopic calls
        var routingCache = new Dictionary<string, RoutingResult>(StringComparer.OrdinalIgnoreCase);
        var candidateSet = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var (category, _) in sortedCategories)
        {
            if (!routingCache.TryGetValue(category, out var routing))
            {
                routing = router.RouteByTopic(category, query);
                routingCache[category] = routing;
            }

            foreach (var src in routing.Sources) candidateSet.Add(src);
        }

        // Always include default routing sources as fallback candidates
        if (!routingCache.TryGetValue("default", out var defaultRouting))
        {
            defaultRouting = router.RouteByTopic("default", query);
            routingCache["default"] = defaultRouting;
        }

        foreach (var src in defaultRouting.Sources) candidateSet.Add(src);

        // Score all candidates, cache SourceDefinition lookups for reuse in partition
        var sourceCache = new Dictionary<string, SourceDefinition?>(StringComparer.OrdinalIgnoreCase);
        var scored = candidateSet
            .Select(name =>
            {
                if (!sourceCache.ContainsKey(name))
                    sourceCache[name] = router.GetSource(name);
                return (Name: name, Score: router.ScoreSource(name, intent.Intent, categories, timeSensitivity));
            })
            .OrderByDescending(x => x.Score)
            .ToList();

        // Partition into search and feed using cached source definitions (single pass)
        var searchCandidates = new List<(string Name, double Score)>();
        var feedCandidates = new List<(string Name, double Score)>();
        foreach (var item in scored)
        {
            if (sourceCache.GetValueOrDefault(item.Name)?.Search == true)
                searchCandidates.Add(item);
            else
                feedCandidates.Add(item);
        }

        // Add search sources first (with search queries from sentinel)
        var searchQueries = intentSearchQueries.ToList();
        if (isQA && !string.IsNullOrWhiteSpace(query))
        {
            var rawTerms = query.Trim();
            if (!searchQueries.Any(sq => sq.Contains(rawTerms, StringComparison.OrdinalIgnoreCase) ||
                                         rawTerms.Contains(sq, StringComparison.OrdinalIgnoreCase)))
                searchQueries.Add(rawTerms);
        }

        var maxSearchQueries = isQA ? 4 : 3;

        // For QA, prefer duckduckgo (knowledge search) over gnews (news RSS).
        // Score-based ordering already handles this via intent_affinity.
        foreach (var (name, _) in searchCandidates)
        {
            if (sources.Count >= maxTotalSources) break;

            // Hard-filter: skip archive search sources for roundup+today
            if (isRoundup && router.HasCapability(name, "archive"))
                continue;

            // Hard-filter: skip tech_only search sources when no tech category
            if (!hasTechCategory && router.HasCapability(name, "tech_only"))
                continue;

            // Hard-filter: skip academic search sources for QA/howto (academic papers don't answer trivia)
            if (isQA && router.HasCapability(name, "academic"))
                continue;

            foreach (var sq in searchQueries.Take(maxSearchQueries))
            {
                var mapped = MapYamlSourceToCli(name, defaultRouting, query);
                if (mapped == null) continue;

                var root = mapped.Split(':')[0];

                if (name == "google_news")
                {
                    if (!usedRoots.Contains("gnews"))
                        AddSource(sources, usedRoots, $"gnews:{sq}");
                    else if (!sources.Any(s => s.StartsWith("gnews:", StringComparison.OrdinalIgnoreCase) &&
                                               s.Contains(sq, StringComparison.OrdinalIgnoreCase)))
                        sources.Add($"gnews:{sq}");
                }
                else if (name == "duckduckgo")
                {
                    if (!usedRoots.Contains("search"))
                        AddSource(sources, usedRoots, $"search:{sq}");
                }
                else if (name == "arxiv")
                {
                    if (!usedRoots.Contains("arxiv"))
                    {
                        var topicTerms = ExtractTopicTerms(query);
                        AddSource(sources, usedRoots, !string.IsNullOrEmpty(topicTerms) ? $"arxiv:{topicTerms}" : "arxiv");
                    }
                }
                else if (name == "spaceflight")
                {
                    if (!usedRoots.Contains("spaceflight"))
                        AddSource(sources, usedRoots, "spaceflight");
                }
                else
                {
                    if (!usedRoots.Contains(root))
                        AddSource(sources, usedRoots, mapped);
                }

                break; // One entry per search source
            }
        }

        // If no search queries but we have a query, add a default search
        if (searchQueries.Count == 0 && !string.IsNullOrWhiteSpace(query))
        {
            var topicTerms = ExtractTopicTerms(query);
            if (!string.IsNullOrEmpty(topicTerms))
            {
                if (!usedRoots.Contains("gnews"))
                    AddSource(sources, usedRoots, $"gnews:{topicTerms}");
                if (!usedRoots.Contains("search"))
                    AddSource(sources, usedRoots, $"search:{topicTerms}");
            }
        }

        // For QA/howto, promote knowledge-capability feed sources (e.g., wikipedia) ahead of
        // regular news feeds. Without this, search sources fill slots first and wikipedia ends up
        // last despite having the highest score.
        if (isQA && sources.Count < maxTotalSources)
            foreach (var (name, _) in feedCandidates)
            {
                if (sources.Count >= maxTotalSources) break;
                if (!router.HasCapability(name, "knowledge")) continue;

                var bestRouting = FindBestRouting(name, sortedCategories, defaultRouting, router, query, routingCache);

                var mapped = MapYamlSourceToCli(name, bestRouting, query);
                if (mapped == null) continue;
                var root = mapped.Split(':')[0];
                if (usedRoots.Contains(root)) continue;
                AddSource(sources, usedRoots, mapped);
            }

        // Add remaining feed sources by score
        var maxTotalFeedSources = isSearchOnly ? 0 : isQA ? 3 : maxTotalSources;
        var totalFeedSourcesAdded = 0;

        foreach (var (name, _) in feedCandidates)
        {
            if (sources.Count >= maxTotalSources) break;
            if (totalFeedSourcesAdded >= maxTotalFeedSources) break;

            // Hard-filter: skip tech_only when no tech category
            if (!hasTechCategory && router.HasCapability(name, "tech_only"))
                continue;

            // Hard-filter: skip archive when roundup+today
            if (isRoundup && router.HasCapability(name, "archive"))
                continue;

            var bestRouting = FindBestRouting(name, sortedCategories, defaultRouting, router, query, routingCache);

            var mapped = MapYamlSourceToCli(name, bestRouting, query);
            if (mapped == null) continue;

            var root = mapped.Split(':')[0];
            if (usedRoots.Contains(root)) continue;

            AddSource(sources, usedRoots, mapped);
            totalFeedSourcesAdded++;
        }

        // --- Phase 3: NER entity enrichment (search queries only) ---
        if (nerContext?.HasEntities == true)
            foreach (var eq in nerContext.EntityQueries.Take(2))
            {
                var gnewsQuery = $"gnews:{eq.EntityText}";
                if (!sources.Any(s => s.Contains(eq.EntityText, StringComparison.OrdinalIgnoreCase)))
                    if (sources.Count < maxTotalSources)
                        sources.Add(gnewsQuery);
            }

        // --- Phase 4: Minimum diversity floor ---
        if (!isSearchOnly && sources.Count < 3)
        {
            foreach (var src in defaultRouting.Sources)
            {
                var mapped = MapYamlSourceToCli(src, defaultRouting, query);
                if (mapped == null) continue;

                var root = mapped.Split(':')[0];
                if (usedRoots.Contains(root)) continue;

                AddSource(sources, usedRoots, mapped);
                if (sources.Count >= 4) break;
            }
        }

        var maxSources = isSearchOnly ? 4 : maxTotalSources;
        return sources.Take(maxSources).ToList();
    }

    /// <summary>
    ///     Convert a SentinelIntent into an InterpretedPrompt for backward compatibility
    ///     with the existing pipeline.
    /// </summary>
    public static InterpretedPrompt ToInterpretedPrompt(
        SentinelIntent intent,
        SourceRouter router,
        string query,
        QueryNerContext? nerContext = null)
    {
        var sources = MapToSources(intent, router, query, nerContext);

        // Extract topics from top-weighted categories
        var categories = intent.Categories ?? new Dictionary<string, double>();
        var topics = categories
            .Where(kv => kv.Value >= 0.3)
            .OrderByDescending(kv => kv.Value)
            .Select(kv => kv.Key)
            .ToList();

        return new InterpretedPrompt
        {
            RawPrompt = query,
            Sources = sources,
            Vibe = intent.Tone ?? "neutral",
            SearchQueries = (intent.SearchQueries ?? []).ToList(),
            Websites = [],
            Limit = intent.Limit > 0 ? intent.Limit : 20,
            Topics = topics,
            NerContext = nerContext,
            SentinelIntent = intent,
            GraphScope = QueryTypeDetector.DetectGraphScope(query, intent)
        };
    }

    #region Helpers

    private static void AddSource(List<string> sources, HashSet<string> usedRoots, string source)
    {
        var colonIdx = source.IndexOf(':');
        var root = colonIdx >= 0 ? source[..colonIdx] : source;
        if (usedRoots.Add(root))
            sources.Add(source);
    }

    /// <summary>
    ///     Find the best routing context for a source from the sorted category list.
    ///     Returns the routing rule for the first matching category, or the default routing.
    /// </summary>
    private static RoutingResult FindBestRouting(
        string sourceName,
        List<KeyValuePair<string, double>> sortedCategories,
        RoutingResult defaultRouting,
        SourceRouter router,
        string query,
        Dictionary<string, RoutingResult> routingCache)
    {
        foreach (var (category, _) in sortedCategories)
        {
            if (!routingCache.TryGetValue(category, out var r))
            {
                r = router.RouteByTopic(category, query);
                routingCache[category] = r;
            }

            if (r.Sources.Contains(sourceName, StringComparer.OrdinalIgnoreCase))
                return r;
        }

        return defaultRouting;
    }

    /// <summary>
    ///     Map a YAML source name to CLI source identifier.
    /// </summary>
    internal static string? MapYamlSourceToCli(string yamlSource, RoutingResult routing, string? query)
    {
        return yamlSource switch
        {
            "google_news" => !string.IsNullOrEmpty(query)
                ? $"gnews:{ExtractTopicTerms(query)}"
                : routing.GoogleNewsTopic != null
                    ? $"gnews_topic:{routing.GoogleNewsTopic}"
                    : "gnews",
            "duckduckgo" => !string.IsNullOrEmpty(query)
                ? $"search:{ExtractTopicTerms(query)}"
                : null,
            "bbc" => routing.BbcCategory != null
                ? $"bbc:{routing.BbcCategory}"
                : "bbc",
            "arxiv" => !string.IsNullOrEmpty(query)
                ? $"arxiv:{ExtractTopicTerms(query)}"
                : "arxiv",
            _ => yamlSource // Identity mapping for all other sources
        };
    }

    private static readonly HashSet<string> StopWords = new(StringComparer.OrdinalIgnoreCase)
    {
        "the", "a", "an", "is", "are", "was", "were", "be", "been", "being",
        "have", "has", "had", "do", "does", "did", "will", "would", "could",
        "should", "may", "might", "must", "shall", "can", "need", "dare",
        "about", "for", "with", "what", "how", "why", "when", "where", "who",
        "show", "me", "tell", "give", "get", "find", "search", "scroll",
        "summarize", "summary", "news", "latest", "recent", "today", "now", "on",
        "new", "any", "some", "all", "current", "happening", "update", "updates"
    };

    internal static string ExtractTopicTerms(string? query)
    {
        return ExtractTopicTermsExcluding(query, []);
    }

    internal static string ExtractTopicTermsExcluding(string? query, IEnumerable<string> exclude)
    {
        if (string.IsNullOrWhiteSpace(query)) return "";

        var excludeSet = new HashSet<string>(exclude, StringComparer.OrdinalIgnoreCase);
        var words = query.Split(' ', StringSplitOptions.RemoveEmptyEntries)
            .Where(w => !StopWords.Contains(w) && !excludeSet.Contains(w) && w.Length > 1)
            .ToList();
        return words.Count > 0 ? string.Join(" ", words) : "";
    }

    #endregion
}